apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o7w7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o7w7
    app.kubernetes.io/part-of: tkwch-fix-0075-0067-app
  name: devfile-sample-o7w7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o7w7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o7w7
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0067-tenant/tkwch-fix-0075-0067-app/devfile-sample-o7w7@sha256:de7011c1ddd806604cf1fa5b9d6dd876d640a897ec8501c024060bbcde03ffd8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
